#ifndef __M_CONFIG_VALUES_H__
#define __M_CONFIG_VALUES_H__

#include "emu/emu.h"
#include "gui/gui.h"
#include "config_types.h"

//--------------------------------------------------------------------------------------------------------
//                          Control default config values
//--------------------------------------------------------------------------------------------------------
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_UP RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_UP)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_DOWN RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_DOWN)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_LEFT RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_LEFT)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_RIGHT RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_RIGHT)

#if defined(FC_BUILD) || defined(GBC_BUILD) || defined(NGP_BUILD)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_B RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_A)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_A RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_B)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_Y TURBO_RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_A)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_X TURBO_RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_B)
#if defined(FC_BUILD)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_L)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_R)
#else
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L1 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R1 0
#endif
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L2 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R2 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L3 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R3 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_SELECT RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_SELECT)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_START RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_START)
#elif defined(SFC_BUILD)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_B RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_A)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_A RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_B)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_Y RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_X)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_X RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_Y)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_L)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_R)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L2 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R2 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L3 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R3 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_SELECT RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_SELECT)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_START RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_START)
#elif defined(GBA_BUILD)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_B RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_A)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_A RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_B)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_Y TURBO_RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_A)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_X TURBO_RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_B)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_L)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_R)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L2 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R2 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L3 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R3 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_SELECT RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_SELECT)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_START RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_START)
#elif defined(MD_BUILD)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_B RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_A)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_A RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_B)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_Y RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_X)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_X RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_Y)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_L)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_R)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L2 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R2 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L3 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R3 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_SELECT RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_SELECT)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_START RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_START)
#elif defined(WSC_BUILD)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_B RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_A)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_A RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_B)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_Y TURBO_RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_A)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_X TURBO_RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_B)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L1 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R1 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L2 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R2 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L3 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R3 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_SELECT 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_START RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_START)
#elif defined(PCE_BUILD)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_B RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_A)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_A RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_B)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_Y RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_X)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_X RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_Y)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_L)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_R)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L2 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R2 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L3 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R3 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_SELECT RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_SELECT)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_START RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_START)
#elif defined(ARC_BUILD)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_B RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_A)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_A RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_B)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_Y RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_X)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_X RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_Y)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_L)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_R)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L2 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_L2)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R2 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_R2)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L3 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R3 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_SELECT RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_SELECT)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_START RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_START)
#elif defined(PS_BUILD)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_B RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_A)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_A RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_B)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_Y RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_X)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_X RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_Y)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_L)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_R)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L2 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_L2)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R2 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_R2)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L3 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_L3)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R3 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_R3)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_SELECT RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_SELECT)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_START RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_START)
#else
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_B RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_A)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_A RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_B)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_Y RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_X)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_X RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_Y)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_L)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R1 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_R)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L2 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_L2)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R2 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_R2)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_L3 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_L3)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_R3 RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_R3)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_SELECT RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_SELECT)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_START RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_START)
#endif

#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_LEFT_ANALOG_UP RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_UP)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_LEFT_ANALOG_DOWN RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_DOWN)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_LEFT_ANALOG_LEFT RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_LEFT)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_LEFT_ANALOG_RIGHT RETRO_BITMASK_KEY(RETRO_DEVICE_ID_JOYPAD_RIGHT)
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_RIGHT_ANALOG_UP 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_RIGHT_ANALOG_DOWN 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_RIGHT_ANALOG_LEFT 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BUTTON_RIGHT_ANALOG_RIGHT 0

#if defined(PS_BUILD)
#define DEFAULT_CONFIG_VALUE_CONTROL_FRONT_TOUCH_PAD 1
#define DEFAULT_CONFIG_VALUE_CONTROL_BACK_TOUCH_PAD 1
#else
#define DEFAULT_CONFIG_VALUE_CONTROL_FRONT_TOUCH_PAD 0
#define DEFAULT_CONFIG_VALUE_CONTROL_BACK_TOUCH_PAD 0
#endif

#define DEFAULT_CONFIG_VALUE_CONTROL_TURBO_DELEY 4
#define DEFAULT_CONFIG_VALUE_CONTROL_CTRL_PLAYER 0

//--------------------------------------------------------------------------------------------------------
//                          Graphics default config values
//--------------------------------------------------------------------------------------------------------
#define DEFAULT_CONFIG_VALUE_GRAPHICS_DISPLAY_SIZE TYPE_DISPLAY_SIZE_FULL
#define DEFAULT_CONFIG_VALUE_GRAPHICS_DISPLAY_RATIO TYPE_DISPLAY_RATIO_DEFAULT
#define DEFAULT_CONFIG_VALUE_GRAPHICS_DISPLAY_ROTATE TYPE_DISPLAY_ROTATE_DEFAULT
#define DEFAULT_CONFIG_VALUE_GRAPHICS_GRAPHICS_SHADER 0
#define DEFAULT_CONFIG_VALUE_GRAPHICS_GRAPHICS_SMOOTH 0
#define DEFAULT_CONFIG_VALUE_GRAPHICS_OVERLAY_SELECT 0
#define DEFAULT_CONFIG_VALUE_GRAPHICS_OVERLAY_MODE TYPE_GRAPHICS_OVERLAY_MODE_OVERLAY
#define DEFAULT_CONFIG_VALUE_GRAPHICS_SHOW_FPS 0

//--------------------------------------------------------------------------------------------------------
//                          Hotkey default config values
//--------------------------------------------------------------------------------------------------------
#define DEFAULT_CONFIG_VALUE_HOTKEY_SAVE_STATE (GUI_CTRL_BUTTON_HOME | GUI_CTRL_BUTTON_X)
#define DEFAULT_CONFIG_VALUE_HOTKEY_LOAD_STATE (GUI_CTRL_BUTTON_HOME | GUI_CTRL_BUTTON_Y)
#define DEFAULT_CONFIG_VALUE_HOTKEY_SPEED_UP (GUI_CTRL_BUTTON_HOME | GUI_CTRL_BUTTON_R1)
#define DEFAULT_CONFIG_VALUE_HOTKEY_SPEED_DOWN (GUI_CTRL_BUTTON_HOME | GUI_CTRL_BUTTON_L1)
#define DEFAULT_CONFIG_VALUE_HOTKEY_REWIND_GAME TURBO_LOCAL_BITMASK_KEY(GUI_CTRL_BUTTON_RIGHT_ANLOG_LEFT) // 回退功能使用连发
#define DEFAULT_CONFIG_VALUE_HOTKEY_CONTROLLER_UP (GUI_CTRL_BUTTON_HOME | GUI_CTRL_BUTTON_RIGHT_ANLOG_UP)
#define DEFAULT_CONFIG_VALUE_HOTKEY_CONTROLLER_DOWN (GUI_CTRL_BUTTON_HOME | GUI_CTRL_BUTTON_RIGHT_ANLOG_DOWN)
#define DEFAULT_CONFIG_VALUE_HOTKEY_EXIT_GAME (GUI_CTRL_BUTTON_HOME | GUI_CTRL_BUTTON_A)

//--------------------------------------------------------------------------------------------------------
//                          Misc default config values
//--------------------------------------------------------------------------------------------------------
#define DEFAULT_CONFIG_VALUE_MISC_AUTO_SAVE_LOAD 1
#define DEFAULT_CONFIG_VALUE_MISC_ENABLE_REWIND 1
#define DEFAULT_CONFIG_VALUE_MISC_REWIND_MAX_COUNT 100
#define DEFAULT_CONFIG_VALUE_MISC_REWIND_INTERVAL_TIME 1

//--------------------------------------------------------------------------------------------------------
//                          App default config values
//--------------------------------------------------------------------------------------------------------
#define DEFAULT_CONFIG_VALUE_APP_PREVIEW_PATH TYPE_PREVIEW_PATH_AUTO
#define DEFAULT_CONFIG_VALUE_APP_PREVIEW_SCALE_TYPE TYPE_PREVIEW_SCALE_TYPE_FIT_CENTER_INSIDE
#define DEFAULT_CONFIG_VALUE_APP_APP_LOG 1
#define DEFAULT_CONFIG_VALUE_APP_CORE_LOG 0
#if defined(FBA_BUILD)
#define DEFAULT_CONFIG_VALUE_APP_SHOW_LOG 1
#else
#define DEFAULT_CONFIG_VALUE_APP_SHOW_LOG 0
#endif
#define DEFAULT_CONFIG_VALUE_APP_LANGUAGE 0

#endif
